# Generated by Django 5.0.2 on 2024-03-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0007_husband_women_husband'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
